mysql:
  url: ""
  pool:
    max: 20
    idle: 10
    timeout:
      idle: 60
      life: 60

redis:
  host:
  port:
  password:
  database: 5
  timeout: 1000
  pool:
    min: 3
    max: 20
    idle: 10
    timeout: 300

mongo:
  url:
  database:
  pool_max: 20